defaults:
  - _self_
  - data: default
  - model: resnet18
  - method: erm
  - train: default

hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}

seed: 42
debug: false
